version: "2"
services:
  geth-bootnode:
    hostname: geth-bootnode
    environment:
      - nodekeyhex=${BOOTNODE_KEY_HEX} #Needs to be fix, so that the miners know the resulting enode id
      - BOOTNODE_IP=${BOOTNODE_IP}
      - PORT=${BOOTNODE_PORT}
    build: pocr-network/bootnode
    container_name: geth-bootnode
    ports:
      - ${BOOTNODE_PORT}:${BOOTNODE_PORT}/udp
      - 31303:30303/udp
    networks:
      chainnet:
        ipv4_address: 172.25.0.101 # The miners need to know the IP address later on
  sealer-1:
    hostname: sealer-1
    depends_on:
      - geth-bootnode
    environment:
      - address=${WALLET_MINER_1} #derived from the private key which is passed in the args
      - password=${PASS_PKEY_MINER_1}
      - bootnodeId=${BOOTNODE_ID} #derived from the nodekeyhex of the bootnode
      - bootnodeIp=${BOOTNODE_IP}
      - bootnodePort=${BOOTNODE_PORT}
      - networkId=${NETWORK_ID}
      - verbosity=3
    image: sealer
    build:
      context: ./pocr-network/sealer
      target: ${SEALER_TARGET}
      args:
        GITLAB_USER: ${GITLAB_USER}
        GITLAB_ACCESS_TOKEN: ${GITLAB_ACCESS_TOKEN}
    container_name: sealer-1
    ports:
      - 8641:8545
      - 8642:8546
    volumes:
      - ${MOUNT_GENESIS_FILE_PATH}:/root/genesis.json:ro
      - ${MOUNT_DATADIR_NODE_1}:/root/.ethereum/
      - ${MOUNT_KEYSTORE_PATH}:/app/keystore:ro
    networks:
      chainnet:
        ipv4_address: 172.25.0.102 # The monitor needs to know this address
  sealer-2:
    hostname: sealer-2
    depends_on:
      - geth-bootnode
    environment:
      - address=${WALLET_MINER_2} #derived from the private key which is passed in the args
      - password=${PASS_PKEY_MINER_2}
      - bootnodeId=${BOOTNODE_ID} #derived from the nodekeyhex of the bootnode
      - bootnodeIp=${BOOTNODE_IP}
      - bootnodePort=${BOOTNODE_PORT}
      - networkId=${NETWORK_ID}
      - verbosity=3
    image: sealer
    container_name: sealer-2
    ports:
      - 8643:8545
      - 8644:8546
    volumes:
      - ${MOUNT_GENESIS_FILE_PATH}:/root/genesis.json:ro
      - ${MOUNT_DATADIR_NODE_2}:/root/.ethereum/
      - ${MOUNT_KEYSTORE_PATH}:/app/keystore:ro
    networks:
      chainnet:
        ipv4_address: 172.25.0.103
 
  sealer-3:
    hostname: sealer-3
    depends_on:
      - geth-bootnode
    environment:
      - address=${WALLET_MINER_3} #derived from the private key which is passed in the args
      - password=${PASS_PKEY_MINER_3}
      - bootnodeId=${BOOTNODE_ID} #derived from the nodekeyhex of the bootnode
      - bootnodeIp=${BOOTNODE_IP}
      - bootnodePort=${BOOTNODE_PORT}
      - networkId=${NETWORK_ID}
      - verbosity=3
    image: sealer
    container_name: sealer-3
    ports:
      - 8645:8545
      - 8646:8546
    volumes:
      - ${MOUNT_GENESIS_FILE_PATH}:/root/genesis.json:ro
      - ${MOUNT_DATADIR_NODE_3}:/root/.ethereum/
      - ${MOUNT_KEYSTORE_PATH}:/app/keystore:ro
    networks:
      chainnet:
        ipv4_address: 172.25.0.104
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp/portainer:/data
    ports:
      - 9000:9000
networks:
  chainnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24