name: Build and publish sealer docker image
on:
  push:
    branches:
    - main
    paths:
      - pocr-network/sealer/**/*

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: int128/kaniko-action@v1
        with:
          tags: ghcr.io/ethereum-pocr/ethereum-pocr.github.io/sealer:latest
          context: pocr-network/sealer
          