name: Genesis for local

on:
  push:
    branches:
    - main
    paths:
      - sc-carbon-footprint/**/*
      - pocr-network/genesis/**/*

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: node:16.8

    steps:
      - uses: actions/checkout@v3
      - name: install solc
        run: |
          apt-get update && apt-get install gettext jq -y && \
          curl -L -o solc-file https://github.com/ethereum/solc-bin/raw/gh-pages/linux-amd64/solc-linux-amd64-latest && \
          curl -o solc -L https://github.com/ethereum/solc-bin/raw/gh-pages/linux-amd64/$(cat solc-file) && \
          chmod +x solc && mv solc /bin/solc
      - name: build Governance smartcontracts
        run: |
          cd sc-carbon-footprint/ && npm install -g solc &&  npm ci && ./build.sh && \
          export GIT_HEAD_HASH=$(git rev-parse  HEAD) && \
          node prepare-genesis.js ../pocr-network/genesis/local-conf.json > genesis-local.final.json 
      - name: publish local.json genesis with Governance smartcontracts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sc-carbon-footprint/genesis-local.final.json
          asset_name: genesis-local.json
          tag: ${{ github.ref }}
          overwrite: true
          body: "publish genesis-local.json with latest Goverance smartcontracts"      