name: Genesis for kerleano

on:
  push:
    branches:
      - "main" # to remove
    tags:        
      - pocrnet
    paths:
      - "pocr-network/genesis/pocrnet-conf.json"
      - "sc-carbon-footprint/**/*"

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: node:16.8

    steps:
      - uses: actions/checkout@v3
      - name: install solc
        run: |
          apt-get update && apt-get install gettext jq -y && \
          # curl -L -o solc-file https://github.com/ethereum/solc-bin/raw/gh-pages/linux-amd64/solc-linux-amd64-latest && \
          curl -L -o solc-file https://github.com/ethereum/solc-bin/raw/gh-pages/linux-amd64/list.txt && \
          curl -o solc -L https://github.com/ethereum/solc-bin/raw/gh-pages/linux-amd64/$(grep v0.8.17 solc-file) && \
          chmod +x solc && mv solc /bin/solc
      - name: build Governance smartcontracts
        run: |
          cd sc-carbon-footprint/ && npm install -g solc &&  npm ci && ./build.sh && \
          export GIT_HEAD_HASH=$(git rev-parse  HEAD) && \
          node prepare-genesis.js ../pocr-network/genesis/pocrnet-conf.json > pocrnet.final.json
      - name: publish genesis pocrnet.json
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sc-carbon-footprint/pocrnet.final.json
          asset_name: pocrnet.json
          tag: ${{ github.ref }}
          overwrite: true
          body: "Release pocrnet.json with latest Goverance smartcontracts"      